package io.github.albertyptang.algorithms.util.collection.linked;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * @author atang
 */
public class LinkedTest {

    private class TestObject {

        private int first;
        private int second;

        private TestObject(final int first, final int second) {
            this.first = first;
            this.second = second;
        }

        @Override // auto-generated by IntelliJ
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            TestObject that = (TestObject) o;

            if (first != that.first) return false;
            return second == that.second;
        }

        @Override // auto-generated by IntelliJ
        public int hashCode() {
            int result = first;
            result = 31 * result + second;
            return result;
        }
    }

    @Test
    public void append() throws Exception {
        final Linked<Long> linked = new Linked<Long>();
        linked.addToTail(null);
        assertEquals(1, linked.size);

        linked.addToTail(2L);
        assertEquals(2, linked.size);
        assertEquals(null, linked.getHead());
        assertEquals((Long) 2L, linked.getTail());
    }

    @Test
    public void prepend() throws Exception {
        final Linked<Long> linked = new Linked<Long>();
        linked.addToHead(null);
        assertEquals(1, linked.size);

        linked.addToHead(2L);
        assertEquals(2, linked.size);
        assertEquals((Long) 2L, linked.getHead());
        assertEquals(null, linked.getTail());
    }

    @Test
    public void delete() throws Exception {
        final Linked<Long> linked = new Linked<Long>();
        linked.addToTail(3L);
        linked.addToTail(4L);
        linked.addToTail(5L);

        linked.deleteTail();
        assertEquals(2, linked.size);
        assertEquals(null, linked.searchFor(5L));

        linked.deleteHead();
        assertEquals(1, linked.size);
        assertEquals(null, linked.searchFor(3L));

        assertEquals((Long) 4L, linked.searchFor(4L)); // middle element still remains

        linked.deleteHead();
        linked.deleteTail();
        linked.deleteHead();
        linked.deleteTail();
        assertEquals(0, linked.size);
    }

    @Test
    public void search() throws Exception {
        final Linked<TestObject> linked = new Linked<TestObject>();
        linked.addToTail(new TestObject(1,2));

        final TestObject found = linked.searchFor(new TestObject(1,2));
        assertEquals(new TestObject(1,2), found);

        found.second = 3; // edit the test object within the list.

        final TestObject notFound = linked.searchFor(new TestObject(1,2));
        assertEquals(null, notFound);

        final TestObject foundAgain = linked.searchFor(new TestObject(1,3));
        assertEquals(new TestObject(1,3), foundAgain);
    }
}
